DROP EVENT DELETE_STATISTICS_EVENT;

CREATE EVENT IF NOT EXISTS DELETE_STATISTICS_EVENT
ON SCHEDULE EVERY 1 MINUTE -- AT CURRENT_TIMESTAMP + INTERVAL 1 MINUTE
STARTS CURRENT_TIMESTAMP
DO
delete from videos_estadisticas where
fecha< DATE_SUB(now(), INTERVAL 30 MINUTE);